# Generated by Django 3.1.3 on 2020-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BallotMeasures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
