# Generated by Django 3.1.3 on 2020-12-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0002_auto_20201117_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenPieceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('written_piece',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee.writtenpiece')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee.artwork')),
            ],
        ),
    ]
