# Generated by Django 3.1.4 on 2020-12-14 18:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0005_auto_20201214_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='statement',
            field=tinymce.models.HTMLField(),
        ),
    ]
