# Generated by Django 3.1.4 on 2020-12-14 21:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0006_auto_20201214_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenpiececomment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
