# Generated by Django 3.1.4 on 2020-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0007_auto_20201214_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenpiececomment',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
