# Generated by Django 3.1.4 on 2020-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0009_auto_20201214_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenpiece',
            name='type',
            field=models.CharField(choices=[('OP', 'Op-Ed'), ('HF', 'Historical Fiction')], default='OP',
                                   max_length=20),
            preserve_default=False,
        ),
    ]
