# Generated by Django 3.1.4 on 2020-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Coffee', '0010_writtenpiece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenpiece',
            name='type',
            field=models.CharField(choices=[('Op-Ed', 'Op-Ed'), ('Historical Fiction', 'Historical Fiction')],
                                   max_length=20),
        ),
    ]
