# Generated by Django 3.1.4 on 2021-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='element',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
