# Generated by Django 3.1.4 on 2021-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Elements', '0002_auto_20210113_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
